### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by ooooeaa** [ooooeaa/protospace-40460#1]
https://protospace-40460.onrender.com

**Comment by shodai-ito** [comment]
@ooooeaa さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
- [x] **ログイン・ログアウトの状態に関わらず、ユーザーの詳細ページには、そのユーザーの詳細情報（名前・プロフィール・所属・役職）と、そのユーザーが投稿したプロトタイプが表示されていること**
プロトタイプ投稿者名をクリックした時の遷移先が、該当のユーザーと異なっております。
Uploading 画面収録 2024-05-20 9.18.31.mov…

修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう！
修正内容が反映されていることを確認できましたら以下のProtoSpace完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by ooooeaa** [comment]
修正箇所依頼に添付いただいた動画が見れず、指摘いただいているエラーを正確に理解できているかわかりません。（申し訳ありません。。。）が、ご指摘いただいてから自身でもエラーが確認でき、修正しました。

修正箇所が不足している場合は再度ご指摘よろしくお願いいたします。

**Comment by mo1015** [comment]
@ooooeaa さん、ご提出ありがとうございます‼︎
添付動画に不備があり申し訳ございませんでした。
前回依頼箇所の修正は確認できました！

今回新たに修正していただきたい箇所がありましたので、再度以下のご確認をお願いいたします。

[修正依頼箇所]

- [x] **ログイン・ログアウトの状態に関わらず、ユーザーの詳細ページには、そのユーザーの詳細情報（名前・プロフィール・所属・役職）と、そのユーザーが投稿したプロトタイプが表示されていること**
所属・役職が正しく表示されていません。
（所属として入力した情報が役職の欄に、役職として入力した情報が所属の欄に表示されています）

修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう！
修正内容が反映されていることを確認できましたら以下のProtoSpace完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by ooooeaa** [comment]
ご指摘ありがとうございます。修正いたしましたのでご確認よろしくお願いします。

**Comment by shodai-ito** [comment]
@ooooeaa さん、ご提出ありがとうございます‼︎
正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
